# added some additional config vars in web for purging logs periodically
# otherwise derived from https://github.com/concourse/concourse-docker/blob/master/docker-compose.yml

version: '3' 

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: XXX
      POSTGRES_USER: XXX
      POSTGRES_PASSWORD: XXX
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    image: concourse/concourse
    command: web
    links: [db]
    depends_on: [db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_EXTERNAL_URL: http://123.123.123.123:8080/
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: XXX
      CONCOURSE_POSTGRES_PASSWORD: XXX
      CONCOURSE_POSTGRES_DATABASE: XXX
      CONCOURSE_ADD_LOCAL_USER: myuser:XXX
      CONCOURSE_MAIN_TEAM_LOCAL_USER: myuser
      CONCOURSE_MAX_DAYS_TO_RETAIN_BUILD_LOGS: 10
      CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN: 10
      CONCOURSE_MAX_BUILD_LOGS_TO_RETAIN: 10
      SECRET_KEY2: 1111111111111111
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [web]
    volumes: ["./keys/worker:/concourse-keys"]
    links: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      SECRET_KEY: 11111111111111
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
