---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu, tag: 18.04}

inputs:
- name: xtensor
- name: xtl
- name: xtl_task

outputs:
- name: miniconda_xtl
  path: miniconda

run:
  path: xtl_task/script.sh
  args: []